site_name: Dropwizard-guicey
site_description: 'Dropwizard guice integration'
site_author: 'Vyacheslav Rusakov'
site_url: 'https://xvik.github.io/dropwizard-guicey'
edit_uri: edit/master/src/doc/docs/

# Repository
repo_name: 'dropwizard-guicey'
repo_url: 'https://github.com/xvik/dropwizard-guicey'

# Copyright
copyright: 'Copyright &copy; 2014-2021 Vyacheslav Rusakov'

# Documentation and theme
theme:
  name: 'material'


# Options
extra:
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xvik
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vyarus


# Google Analytics
google_analytics:
  - 'UA-93174150-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

nav:
    - Home: index.md
    - Getting started: getting-started.md
    - Concepts overview: concepts.md
    - User guide:
      - Configuration: guide/configuration.md
      - Integration lifecycle: guide/lifecycle.md
      - Injector: guide/injector.md
      - Module autowiring: guide/module-autowiring.md
      - Bindings: guide/bindings.md
      - Classpath scan: guide/scan.md
      - Installers: guide/installers.md
      - Ordering: guide/ordering.md
      - Bundles (Guicey): guide/bundles.md
      - Options: guide/options.md
      - Diagnostic: guide/diagnostic.md
      - Lifecycle events: guide/events.md
      - Commands: guide/commands.md
      - Web: guide/web.md
      - Test: guide/test.md
      - Migration from dropwizard-guice: guide/dg-migration.md
    - Installers:
      - Resource: installers/resource.md
      - Task: installers/task.md
      - Managed: installers/managed.md
      - Lifecycle: installers/lifecycle.md
      - Health check: installers/healthcheck.md
      - Jersey extension: installers/jersey-ext.md
      - Jersey feature: installers/jersey-feature.md
      - Eager singleton: installers/eager.md
      - Plugin: installers/plugin.md
      - Web servlet: installers/servlet.md
      - Web filter: installers/filter.md
      - Web listener: installers/listener.md
    - Examples:
      - Authentication: examples/authentication.md
      - Governator: examples/governator.md
      - Hibernate: examples/hibernate.md
      - EventBus: examples/eventbus.md
      - JDBI: examples/jdbi.md
      - JDBI3: examples/jdbi3.md
    - Extras:
      - Admin REST: extras/admin-rest.md
      - BOM: extras/bom.md
      - Lifecycle annotations: extras/lifecycle-annotations.md
      - Guava EventBus: extras/eventbus.md
      - JDBI: extras/jdbi.md
      - JDBI3: extras/jdbi3.md
      - SPA: extras/spa.md
      - Server Pages: extras/gsp.md
    - About:
      - Compatibility: about/compatibility.md
      - Release notes: about/history.md
      - Support: about/support.md
      - License: about/license.md